# Generated by Django 5.1.3 on 2025-07-18 08:31

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_hcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcs',
            name='hcs_number',
            field=models.CharField(default=payments.models.fine_number_generator, max_length=20, unique=True),
        ),
    ]
