# Generated by Django 5.1.3 on 2025-07-18 09:15

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='parking_number',
            field=models.CharField(default=payments.models.fine_number_generator, max_length=20, unique=True),
        ),
    ]
