# Generated by Django 5.1.3 on 2025-07-18 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_parking_parking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='parking_number',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', message='Номер парковки должен содержать ровно 4 цифры')]),
        ),
    ]
