# Generated by Django 5.1.3 on 2025-06-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_number',
            field=models.CharField(editable=False, max_length=16, unique=True),
        ),
    ]
