# Generated by Django 5.1.3 on 2025-06-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_profile_picture_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('moderator', 'Moderator')], default='client', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
