# Generated by Django 5.1.3 on 2025-06-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.CharField(default=459067, max_length=6),
            preserve_default=False,
        ),
    ]
