# Generated by Django 5.1.3 on 2025-07-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
